api_user_list:
    path: /api/user/list
    controller: App\API\Controller\User\ListController
    methods: [GET]
    options:
        expose: true
api_user_delete:
    path: /api/user/delete/{id}
    controller: App\API\Controller\User\DeleteController
    methods: [DELETE]
    requirements:
        id: '\d+'
    options:
        expose: true
